name: Release
on:
  push:
    branches:
      - main

jobs:
  detect-secrets:
    name: Detect Secrets
    uses: ./.github/workflows/_detect-secrets.yml

  install-dependencies:
    name: Install Dependencies
    uses: ./.github/workflows/_install-dependencies.yml

  code-qa:
    name: Code QA
    needs: [detect-secrets, install-dependencies]
    uses: ./.github/workflows/_code-qa.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}
      node-version: ${{ needs.install-dependencies.outputs.node-version }}

  release:
    name: Release
    needs: [install-dependencies, code-qa]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ needs.install-dependencies.outputs.node-version }}

      - name: Restore node_modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: node-modules-${{ needs.install-dependencies.outputs.cache-key }}

      - name: Build project
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
